version: 1
labels:
  - label: "size-xs"
    size-below: 5
  - label: "size-s"
    size-above: 4
    size-below: 10
  - label: "size-m"
    size-above: 9
    size-below: 20
  - label: "size-l"
    size-above: 19
