name: Auto Label PR based on File Changes
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  Label-PR:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/pr-labeler-based-on-multiple-rules
      - uses: srvaroa/labeler@v0.8
        with:
          config_path: .github/labeler_config.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
